version: "3.9"
services:
  bot:
    build: .
    depends_on:
      - database
    restart: always
  database:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: agp
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    
volumes:
  db-data: {}