services:
  bot:
    build: .
    depends_on:
      - database
    restart: always
    network_mode: "host"
    environment:
      - "BOT_TOKEN=${BOT_TOKEN}"
  database: 
    image: postgres:15.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: agp
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
